import{PrismaClient,GameLanguage}from"@prisma/client";const p=new PrismaClient();const words={arabic: [
  "محاجب", "دبزين", "فرملة", "خرفان", "بزاف",
  "قهوة", "خبزة", "كسرة", "شخشوخة", "حريرة",
  "طاجين", "بركوكس", "مقرود", "زلابية", "مسمن",
  "بطاطا", "طماطم", "بصل", "فلفل", "زيتون",
  "دجاج", "لحم", "حوت", "بيض", "حليب",
  "دار", "باب", "سطح", "بيت", "زنقة",
  "حومة", "درب", "سوق", "حانوت", "قهوة",
  "صاحب", "خويا", "ختي", "ولد", "بنت",
  "صحاب", "عائلة", "خدمة", "قراية", "جامعة",
  "مدرسة", "كتاب", "قلم", "كرسي", "طاولة",
  "سيارة", "طاكسي", "طريق", "دراجة", "روطار",
  "بلاص", "درك", "اليوم", "غدوة", "دوكا",
  "بصح", "علاش", "واش", "وين", "كيفاش",
  "شحال", "علاه", "هكذا", "صحيت", "يعطيك",
  "مليح", "مليحة", "كبير", "صغير", "ساهل",
  "صعيب", "سريع", "بطيء", "بعيد", "قريب",
  "فرحان", "حزين", "عيان", "بردان", "سخون",
  "نعسان", "جيعان", "عطشان", "مخلوع", "مقلق"
],arabizi: [
  "SAHBI", "DZAIR", "BARDO", "MHAJB",
  "KHOYA", "S7ABI", "KHTI", "WELD", "BENT",
  "DAR", "BAB", "SOU9", "HOMA", "ZAN9A",
  "KAHWA", "KHOBZA", "KESRA", "TAJIN", "CHAKHCHOUKHA",
  "MA9ROUD", "ZLABIA", "MSEMEN", "BATATA", "BSEL",
  "FELFEL", "DJEDJ", "LA7M", "7OUT", "BID",
  "7LIB", "ZITOUN", "KHDMA", "9RAYA", "JAM3A",
  "MDRSA", "KTAB", "9ALAM", "KORSI", "TABLA",
  "TONOBIL", "TAXI", "TRI9", "BLAÇA", "DORK",
  "LYOUM", "GHEDWA", "DOKA", "BSA7", "3LACH",
  "WACH", "WIN", "KIFACH", "CH7AL", "S7I7",
  "MELI7", "KBIR", "S8IR", "SAHEL", "S3IB",
  "SRI3", "B3ID", "9RIB", "FER7AN", "7ZIN",
  "3AYAN", "BERDAN", "S5OUN", "N3SAN", "J3AN",
  "3TCHAN", "M9ALA9", "M5LO3"
]};for(const [language,list]of Object.entries(words))for(const text of list)await p.word.upsert({where:{text_language:{text,language:language as GameLanguage}},update:{isActive:true},create:{text,language:language as GameLanguage,length:Array.from(text).length}});await p.$disconnect();
